version: '3'

includes:
  infra:
    taskfile: $TEDA_TASK_INFRA
    internal: true

tasks:
  apply:
    desc: Apply the crossplane configuration to the cluster
    deps: [infra:create]
    cmds:
      - kubectl apply --filename apis
      - kubectl wait --for=condition=established compositeresourcedefinition/xmanagementclusters.cfg.tedatech.app --timeout=5s
      - kubectl apply --filename examples
      - kubectl wait --for=condition=healthy provider.pkg.crossplane.io --all --timeout=120s
      - |
        kubectl create --namespace crossplane configmap crossplane-go-templates \
          --from-file=templates \
          --output yaml \
          --dry-run=client \
          | kubectl apply -f -
      - kubectl wait --for=condition=healthy function.pkg.crossplane.io --all --timeout=120s
