version: '3'

includes:
  infra:
    taskfile: $TEDA_TASK_INFRA
    internal: true

tasks:
  apply:
    desc: Apply the crossplane configuration to the cluster
    deps: [infra:create]
    cmds:
      - task: apply-apis
      - task: apply-templates
      - task: apply-configurations

  apply-apis:
    internal: true
    sources:
      - 'apis/*.yaml'
      - 'apis/**/*.yaml'
    cmds:
      - kubectl apply --filename apis
      - kubectl wait --for=condition=established compositeresourcedefinition/xmanagementclusters.cfg.tedatech.app --timeout=5s

  apply-templates:
    internal: true
    sources:
      - 'templates/*.goyml'
      - 'templates/**/*.goyml'
    cmds:
      - |
        kubectl create --namespace crossplane configmap crossplane-go-templates \
          --from-file=templates \
          --output yaml \
          --dry-run=client \
          | kubectl apply -f -

  apply-configurations:
    internal: true
    sources:
      - 'examples/*.yaml'
      - 'examples/**/*.yaml'
    cmds:
      - kubectl apply --filename examples/functions.yaml
      - kubectl apply --filename examples/providers.yaml
      - kubectl wait --for=condition=healthy functions.pkg.crossplane.io --all --timeout=120s
      - kubectl wait --for=condition=healthy providers.pkg.crossplane.io --all --timeout=120s
      - kubectl apply --filename examples/provider-config.yaml

  test:
    desc: Run the chainsaw tests
    deps: [apply]
    status:
        # Ensures test command is always rerun when started
        - false
    cmds:
        - chainsaw test {{.CLI_ARGS}}
    # When using --watch we want to rerun on all changes
    sources:
      - 'tests/**/*.yaml'
      - 'examples/*.yaml'
      - 'examples/**/*.yaml'
      - 'templates/*.goyml'
      - 'templates/**/*.goyml'
      - 'apis/*.yaml'
      - 'apis/**/*.yaml'
