kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/lib/docker/volumes/kind-containerd-data/_data
      containerPath: /var/lib/containerd
    - hostPath: $APP_ROOT
      containerPath: /app
      readOnly: true
    - hostPath: $MKCERT_ROOT_CA_CERT
      containerPath: /usr/local/share/ca-certificates/mkcert-ca.crt
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "service-node-port-range": "0-32767"
