version: '3'

vars:
  KUBERNETES_VERSION: '{{.KUBERNETES_VERSION | default "v1.31.1"}}'
  CILIUM_VERSION: '{{.CILIUM_VERSION | default "1.16.3"}}'

tasks:
  create:
    desc: Create cluster and configure, root-ca secret and install crossplane
    cmds:
      - task: cluster-create
      - task: install-cilium
      - task: install-local-cert
      - task: install-infra

  destroy:
    desc: Destroy the entire cluster, ensure a clean environment
    cmds:
      - kind delete cluster --name {{.CLUSTER_NAME}}

  cluster-create:
    internal: true
    status:
      - kind get clusters | grep {{.CLUSTER_NAME}}
    cmds:
      - |
        kind create cluster \
          --name {{.CLUSTER_NAME}} \
          --image kindest/node:{{.KUBERNETES_VERSION}} \
          --config=$TEDA_KIND_CONFIG

  install-cilium:
    internal: true
    status:
      - cilium status
    cmds:
      - cilium install --version {{.CILIUM_VERSION}}

  install-local-cert:
    internal: true
    status:
      - kubectl get secret --namespace cert-manager root-ca
    cmds:
      - mkcert -install
      - kubectl create namespace cert-manager || true
      - |
        kubectl create secret tls root-ca --namespace cert-manager \
          --key "$(mkcert -CAROOT)/rootCA-key.pem" \
          --cert "$(mkcert -CAROOT)/rootCA.pem" \
          --dry-run=client -o yaml \
          | kubectl apply -f -

  install-infra:
    desc: Setup infra components, as referenced from infra repository
    internal: true
    vars:
      ENVIRONMENT: '{{.ENVIRONMENT | default "staging"}}'
      PATH_QUERY: '{{.PATH_QUERY | default "?ref=main"}}'
      REPOSITORY: '{{.REPOSITORY | default "git@github.com:TedaTech/infra//"}}'
    cmds:
      - kubectl apply -k {{.REPOSITORY}}clusters/{{.ENVIRONMENT}}/flux-system{{.PATH_QUERY}}
      - kubectl apply -k {{.REPOSITORY}}infrastructure/controllers{{.PATH_QUERY}}
      - kubectl wait --for=condition=Ready helmrelease/crossplane -n crossplane --timeout=60s
      - kubectl apply -k {{.REPOSITORY}}infrastructure/configs{{.PATH_QUERY}}
