version: '3'

vars:
  KUBERNETES_VERSION: '{{.KUBERNETES_VERSION | default "v1.31.1"}}'
  CILIUM_VERSION: '{{.CILIUM_VERSION | default "1.16.3"}}'

tasks:
  create:
    desc: Create cluster and configure, root-ca secret and install crossplane
    cmds:
      - task: cluster-create
      - task: install-cilium
      - task: install-local-cert
      - task: install-infra

  destroy:
    desc: Destroy the entire cluster, ensure a clean environment
    cmds:
      - kind delete cluster --name {{.CLUSTER_NAME}}
      # Ensures that on a new cluster all template files are applied
      - rm -Rf .task

  cluster-create:
    internal: true
    status:
      - kind get clusters | grep {{.CLUSTER_NAME}}
    vars:
      TEDA_KIND_CONFIG_TMP:
        sh: mktemp
    cmds:
      - defer: rm "{{ .TEDA_KIND_CONFIG_TMP }}"
      - task: cluster-create-image-cache
      - |
        export SSH_AUTH_SOCK_DIR=$(dirname $SSH_AUTH_SOCK)
        envsubst < "$TEDA_KIND_CONFIG" > "{{ .TEDA_KIND_CONFIG_TMP }}"
        kind get clusters | grep {{.CLUSTER_NAME}} || kind create cluster \
          --name {{.CLUSTER_NAME}} \
          --image kindest/node:{{.KUBERNETES_VERSION}} \
          --config="{{ .TEDA_KIND_CONFIG_TMP }}"

  cluster-create-image-cache:
    internal: true
    status:
      - docker volume inspect kind-containerd-data
    cmds:
      - docker volume create kind-containerd-data

  install-cilium:
    internal: true
    status:
      - cilium status
    vars:
      API_SERVER_IP:
        sh: kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
      API_SERVER_PORT:
        sh: kubectl get svc kubernetes -o jsonpath='{.spec.ports[0].targetPort}'
    cmds:
      - |
        cilium status || cilium install  \
          --version {{.CILIUM_VERSION}} \
          --set kubeProxyReplacement=true \
          --set k8sServiceHost={{.API_SERVER_IP}} \
          --set k8sServicePort={{.API_SERVER_PORT}}

  install-local-cert:
    desc: Uses mkcert to install locally trusted root certificate and exports cert to k8s secret
    internal: true
    status:
      - kubectl get secret --namespace cert-manager root-ca
    cmds:
      - mkcert -install
      - kubectl create namespace cert-manager || true
      - |
        kubectl create secret tls root-ca --namespace cert-manager \
          --key "$(mkcert -CAROOT)/rootCA-key.pem" \
          --cert "$(mkcert -CAROOT)/rootCA.pem" \
          --dry-run=client -o yaml \
          | kubectl apply -f -

  install-infra:
    desc: Setup infra components, as referenced from infra repository
    internal: true
    status:
      - kubectl wait --for=condition=Ready helmrelease/crossplane -n crossplane --timeout=0s
    vars:
      INFRA_CLUSTER: '{{.INFRA_CLUSTER | default "git@github.com/TedaTech/infra.git//clusters/dev/flux-system"}}'
    cmds:
      - kubectl apply -k "{{ .INFRA_CLUSTER }}"
