name: test
on:
  push:
    branches:
    - main
    - beta
    - alpha

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
